-- Haskell module generated by the BNF converter

module Syntax.Skel where

import qualified Syntax.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Syntax.Abs.Ident -> Result
transIdent x = case x of
  Syntax.Abs.Ident string -> failure x
transLam :: Syntax.Abs.Lam -> Result
transLam x = case x of
  Syntax.Abs.Lam string -> failure x
transProd :: Syntax.Abs.Prod -> Result
transProd x = case x of
  Syntax.Abs.Prod string -> failure x
transTo :: Syntax.Abs.To -> Result
transTo x = case x of
  Syntax.Abs.To string -> failure x
transNext :: Syntax.Abs.Next -> Result
transNext x = case x of
  Syntax.Abs.Next string -> failure x
transNapp :: Syntax.Abs.Napp -> Result
transNapp x = case x of
  Syntax.Abs.Napp string -> failure x
transTyp :: Syntax.Abs.Typ -> Result
transTyp x = case x of
  Syntax.Abs.TReal -> failure x
  Syntax.Abs.TNext next typ -> failure x
  Syntax.Abs.TPRod typ1 prod typ2 -> failure x
  Syntax.Abs.TFun typ1 to typ2 -> failure x
transExp :: Syntax.Abs.Exp -> Result
transExp x = case x of
  Syntax.Abs.Var ident -> failure x
  Syntax.Abs.Val integer -> failure x
  Syntax.Abs.Rec ident exp -> failure x
  Syntax.Abs.Abstr lam ident exp -> failure x
  Syntax.Abs.App exp1 exp2 -> failure x
  Syntax.Abs.NApp exp1 napp exp2 -> failure x
  Syntax.Abs.Pair exp1 exp2 -> failure x
  Syntax.Abs.Fst exp -> failure x
  Syntax.Abs.Snd exp -> failure x
  Syntax.Abs.Typed exp typ -> failure x
transAssignment :: Syntax.Abs.Assignment -> Result
transAssignment x = case x of
  Syntax.Abs.Assign ident exp -> failure x
transEnvironment :: Syntax.Abs.Environment -> Result
transEnvironment x = case x of
  Syntax.Abs.Env assignments -> failure x

