-- Haskell module generated by the BNF converter

module Syntax.Skel where

import qualified Syntax.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: Syntax.Abs.Ident -> Result
transIdent x = case x of
  Syntax.Abs.Ident string -> failure x
transLam :: Syntax.Abs.Lam -> Result
transLam x = case x of
  Syntax.Abs.Lam string -> failure x
transMu :: Syntax.Abs.Mu -> Result
transMu x = case x of
  Syntax.Abs.Mu string -> failure x
transProd :: Syntax.Abs.Prod -> Result
transProd x = case x of
  Syntax.Abs.Prod string -> failure x
transTo :: Syntax.Abs.To -> Result
transTo x = case x of
  Syntax.Abs.To string -> failure x
transLater :: Syntax.Abs.Later -> Result
transLater x = case x of
  Syntax.Abs.Later string -> failure x
transLapp :: Syntax.Abs.Lapp -> Result
transLapp x = case x of
  Syntax.Abs.Lapp string -> failure x
transTyp :: Syntax.Abs.Typ -> Result
transTyp x = case x of
  Syntax.Abs.TReal -> failure x
  Syntax.Abs.TVar ident -> failure x
  Syntax.Abs.TLat later typ -> failure x
  Syntax.Abs.TPRod typ1 prod typ2 -> failure x
  Syntax.Abs.TRec mu ident typ -> failure x
  Syntax.Abs.TFun typ1 to typ2 -> failure x
transExp :: Syntax.Abs.Exp -> Result
transExp x = case x of
  Syntax.Abs.Var ident -> failure x
  Syntax.Abs.Val double -> failure x
  Syntax.Abs.Next exp -> failure x
  Syntax.Abs.In exp -> failure x
  Syntax.Abs.Out exp -> failure x
  Syntax.Abs.App exp1 exp2 -> failure x
  Syntax.Abs.LApp exp1 lapp exp2 -> failure x
  Syntax.Abs.Pair exp1 exp2 -> failure x
  Syntax.Abs.Fst exp -> failure x
  Syntax.Abs.Snd exp -> failure x
  Syntax.Abs.Norm exp -> failure x
  Syntax.Abs.Abstr lam exp1 exp2 -> failure x
  Syntax.Abs.Rec exp1 exp2 -> failure x
  Syntax.Abs.Typed exp typ -> failure x
transAssignment :: Syntax.Abs.Assignment -> Result
transAssignment x = case x of
  Syntax.Abs.Assign ident exp -> failure x
transEnvironment :: Syntax.Abs.Environment -> Result
transEnvironment x = case x of
  Syntax.Abs.Env assignments -> failure x

